// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY'] as String,
    appId: '1:18163618911:web:718bcca719f535cefdb7ea',
    messagingSenderId: '18163618911',
    projectId: 'chat-app-78942',
    authDomain: 'chat-app-78942.firebaseapp.com',
    databaseURL: 'https://chat-app-78942-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-78942.appspot.com',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'] as String,
    appId: '1:18163618911:android:a80e7799e61a293afdb7ea',
    messagingSenderId: '18163618911',
    projectId: 'chat-app-78942',
    databaseURL: 'https://chat-app-78942-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-78942.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'] as String,
    appId: '1:18163618911:ios:0ad95e1df7cfb17cfdb7ea',
    messagingSenderId: '18163618911',
    projectId: 'chat-app-78942',
    databaseURL: 'https://chat-app-78942-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-78942.appspot.com',
    iosBundleId: 'com.example.aiChatApp',
  );
}
